version: '3'

services:
  users:
    build: .
    image: users:latest
    command: python3 -u views.py
    container_name: users
    ports:
      - "80:80"
    volumes:
      - .:/app_users
    links:
      - mongousers

  mongousers:
    container_name: mongousers
    image: mongo:latest